name: CI Build (main.c changes)

on:
  push:
    paths:
      - 'src/main.c'
  pull_request:
    paths:
      - 'src/main.c'

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential cmake pkg-config \
            libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev \
            libgl1-mesa-dev libglu1-mesa-dev libasound2-dev libpulse-dev \
            libudev-dev libdrm-dev libgbm-dev

      - name: Configure (CMake)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -j

      - name: Install doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate docs (Doxygen)
        run: doxygen ${GITHUB_WORKSPACE}/Doxyfile

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/html
